###
### Print Method for the RCT2 Package
### 
###



#' Print Method for the RCT2 Package
#'
#' 
#' This function prints a nicely formatted summary of the three functions in the RCT2 package.
#'
#' 
#' For the details of the method implemented by this function, see the
#' references.
#' 
#' @param x A list object generated by running one of the analyses on a data set.
#' @return \code{NULL}
#' @author Kosuke Imai, Department of Statistics, Harvard University
#' \email{imai@harvard.edu}, \url{https://imai.fas.harvard.edu/};
#' Zhichao Jiang, School of Public Health and Health Sciences, University of Massachusetts Amherst
#' \email{zhichaojiang@umass.edu};
#' Karissa Huang, Department of Statistics, Harvard College
#' \email{krhuang@college.harvard.edu}
#' @references Kosuke Imai, Zhichao Jiang and Anup Malani (2018).
#' \dQuote{Causal Inference with Interference and Noncompliance in the Two-Stage Randomized Experiments}, \emph{Technical Report}. Department of Politics, Princeton
#' University.
#' @keywords two-stage randomized experiments
#' @export




#' @method print regression
print.regression <- function(x, ...){
  CIs <- c(x$CADE1.CI, x$CADE0.CI)
  CADEs <- c(x$CADE1, x$CADE0)
  name <- c("CADE1", "CADE0")
  variances <- c("Cluster Robust Variance", "HC2 Variance", "Cluster Robust HC2 Variance", "Individual Variance", "Proposed Variance")
  cluster_robust_variance <- c(x$var1.clu, x$var0.clu)
  HC2_variance <- c(x$var1.hc2, x$var0.hc2)
  cluster_robust_HC2_variance <- c(x$var1.clu.hc2, x$var0.clu.hc2)
  individual_variance <- c(x$var1.ind, x$var0.ind)
  proposed_variance <- c(x$var1.reg, x$var0.reg)
  variance_values <- as.data.frame(rbind(cluster_robust_variance, HC2_variance, cluster_robust_HC2_variance, individual_variance, proposed_variance))
  names(variance_values) <- c("var(CADE1)", "var(CADE0)")
  estimates <- as.data.frame(cbind(name, CADEs, CIs))
  rownames(estimates) <- NULL
  # out <- list(estimates, variance_values)
  return("Test")
}

#' @method print random
print.random <- function(x, ...){
  variance <- c(x$var.CADE1, x$var.CADE0, x$var.CASE1, x$var.CASE0,x$var.DEY1, x$var.DEY0, x$var.DED1, x$var.DED0, x$var.SEY1, x$var.SEY0, x$var.SED1, x$var.SED0)
  stds <- sqrt(variance)
  estimate <- c(x$CADE1, x$CADE0, x$CASE1, x$CASE0, x$DEY1, x$DEY0, x$DED1, x$DED0, x$SEY1, x$SEY0, x$SED1, x$SED0)
  name <- c("CADE1", "CADE0", "CASE1", "CASE0", "DEY1", "DEY0", "DED1", "DED0", "SEY1", "SEY0", "SED1", "SED0")
  
  variance <- round(variance, 5)
  stds <- round(stds, 5)
  estimate <- round(estimate, 5)
  lcis <- c(x$lci.CADE1, x$lci.CADE0, x$lci.CASE1, x$lci.CASE0, x$lci.DEY0, x$lci.DEY1, x$lci.SEY0, x$lci.SEY1, x$lci.DED0, x$lci.DED1, x$lci.SED0, x$lci.SED1)
  rcis <- c(x$rci.CADE1, x$rci.CADE0, x$rci.CASE1, x$rci.CASE0, x$rci.DEY0, x$rci.DEY1, x$rci.SEY0, x$rci.SEY1, x$rci.DED0, x$rci.DED1, x$rci.SED0, x$rci.SED1)
  
  out <- as.data.frame(cbind(name, estimate, variance, stds, lcis, rcis))
  return(out)
}





#' @method print parametric
print.parametric <- function(x, ...){
  names <- c("ITT DE", "IV DE", "ITT SE", "IV SE")
  effects <- rbind(x$ITT.DE, x$IV.DE, x$ITT.SE, x$IV.SE)
  CIs <- rbind(x$ITT.DE.CI, x$ITT.SE.CI, x$IV.DE.CI, x$IV.SE.CI)
  init <- as.data.frame(cbind(names, effects, CIs))
  colnames(init) <- c("Method", "Treatment", "Control", "Treatment CI", "Control CI")
  tstat_pvals <- as.data.frame(cbind(x$ITT.pvals, x$ITT.tstat, x$IV.pvals, x$IV.tstat))
  colnames(tstat_pvals) <- c("ITT pvalues", "ITT tstat", "IV pvalues", "IV tstat")
  out <- list(init, tstat_pvals)
  return(out)
}





